[project]
name = "ok-nte"
version = "0.1.0"
description = "An image-recognition-based automation tool for Neverness To Everness"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "comtypes>=1.4.16",
    "librosa>=1.0.0",
    "mido>=1.3.3",
    "ok-script[ocr,qt]>=2.0.1",
    "onnxocr-ppocrv5>=0.0.20",
    "opencc>=1.4.1",
    "opencv-python>=5.0.0.93",
    "openvino>=2026.3.0",
    "psutil>=7.2.2",
    "pynput>=1.8.2",
    "PySide6-Essentials==6.11.2",
    "pyside6-fluent-widgets==1.11.3",
    "scikit-image>=0.26.0",
    "sounddevice>=0.5.6",
    "pywin32==311",
]

[dependency-groups]
dev = [
    "polib>=1.2.0",
    "pytest>=9.1.1",
]

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["E", "F", "I"]

[tool.ruff.format]
quote-style = "double"

[tool.ruff.lint.isort]
known-third-party = ["ok"]

[tool.uv]
environments = [
    "sys_platform == 'win32'"
]

exclude-dependencies = [
    { package = { name = "pyside6-fluent-widgets" },
      dependencies = ["pyside6"] },
]
